### ISSUE TITLE
docker pull error: TLS handshake timeout

### ISSUE THREAD

**Issue by ounie-os** [pnoker/iot-dc3#46]
step1 : git clone master
step2: do as guide
root@ubuntu18:/mnt/iot-dc3/dc3# docker-compose -f docker-compose-demo.yml up -d
Creating network "dc3_dc3net" with driver "bridge"
Pulling web (pnoker/dc3-web:demo)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout

i've no idea that whether the problem of my network or something else ?

**Comment by pnoker** [comment]
镜像仓库在国外，可以配置国内加速源进行加速 ，参考 [如何配置镜像加速](https://github.com/pnoker/iot-dc3/wiki/Docker%E5%8A%A0%E9%80%9F)
