### ISSUE TITLE
dc3使用maven打包的时候报错

### ISSUE THREAD

**Issue by 1131220243** [pnoker/iot-dc3#53]
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.4.8:repackage (default) on project dc3-gateway: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:2.4.8:repackage failed: A required class was missing while executing org.springframework.boot:spring-boot-maven-plugin:2.4.8:repackage: org/apache/maven/shared/artifact/filter/collection/ArtifactsFilter

**Comment by pnoker** [comment]
建议最好不要使用私有服务
