### ISSUE TITLE
demo运行的时候找不到VirturlDriver

### ISSUE THREAD

**Issue by skywayman** [pnoker/iot-dc3#54]
参照文档，使用docker运行demo
#启动
docker-compose -f docker-compose-demo.yml up -d
一切正常，所有需要的服务全部启动

然后进行至：切换至“模版”菜单，点击“新增”，新增一个模版，然后“保存”，例如模版名称为：“Virtual-Profile”，所属驱动选择：“VirturlDriver”
驱动下拉一栏为空，没有“VirturlDriver”。

**Comment by xxsvip** [comment]
同样遇到该问题，不知道上面兄弟解决了没有

**Comment by rushcaomei** [comment]
同样的问题

**Comment by pnoker** [comment]
多等会，demo需要启动很多任务，你可以检查每个依赖服务是否启动正常
