### ISSUE TITLE
这个程序好像没有mqtt接收数据的解析？

### ISSUE THREAD

**Issue by hhxxjjnj** [pnoker/iot-dc3#57]
![image](https://user-images.githubusercontent.com/39041328/186858829-9dcfde36-c7e1-4797-bdd1-8bc25cf8b76a.png)
模拟发数据后，没有收到数据
![image](https://user-images.githubusercontent.com/39041328/186859070-6059f902-0996-4d96-91c7-cb76060498dd.png)
debug调试也进不去（handlerValue）
![image](https://user-images.githubusercontent.com/39041328/186859375-dad817a8-f922-4df3-945d-4d0ad23cd76e.png)

**Comment by pnoker** [comment]
已添加
